name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      
    - name: Make IPA
      run: make
    - uses: actions/upload-artifact@v3
      with:
       name: IPA Download
       path: Whitelist.ipa
